username=input('Введите Ваше Имя')
title=input('Введите заголовок заметки:')
content=input('Введите описание заметки:')
status=input('Введите статус заметки:')
created_date=input('Введите дату создания (дд.мм.гг.)"')
issue_date=input('Введите дату окончания (дд.мм.гг.)')